project:
  seed: 12

dataset:
  name: brain-tumor-classification-mri
  url: sartajbhuvaji/brain-tumor-classification-mri

paths:
  raw: data/raw
  models: artifacts/models
  figures: artifacts/figures

preprocessing:
  canonical_image_size: 299
  validation_split: 0.20

training:
  batch_size: 32
  epochs: 30
  learning_rate: 0.0003
  optimizer: adam
  loss_function: categorical_crossentropy
  early_stopping_patience: 8
  reduce_lr_patience: 3
  reduce_lr_factor: 0.5

augmentation:
  rotation_range: 30
  zoom_range: 0.1
  width_shift_range: 0.1
  height_shift_range: 0.1
  horizontal_flip: true
  vertical_flip: false

mlflow:
  experiment_name: "cnn_brain_tumor_classification"
  experiment_path: "cnn_brain_tumor_classification"

huggingface:
  repo_id: "pazaborgs/brain_tumor_classification_V2"

models:
  - name: cnn_custom
    image_size: 128
    preprocessing: rescale
    last_conv_layer: last_feature_map
  - name: inception_v3
    image_size: 299
    preprocessing: inception_v3
    last_conv_layer: mixed10
  - name: efficientnet_b0
    image_size: 224
    preprocessing: efficientnet
    last_conv_layer: top_conv
  - name: densenet121
    image_size: 224
    preprocessing: densenet
    last_conv_layer: relu
